Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:

In [2]:
import numpy as np

1. Initialize an empty array with size 2X2.

In [3]:

a=np.empty((2,2))
a
# array.shape



array([[5.01640820e-310, 0.00000000e+000],
       [5.01762585e-310, 6.60977373e-310]])

2. Initialize an all one array with size 4X2.

In [4]:
array=np.ones((4,2))
array


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [5]:
a=np.full((4,3),3)
a

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [6]:
i=np.arange(6).reshape(2,3)

a=np.zeros_like(i)
a

array([[0, 0, 0],
       [0, 0, 0]])

5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
i=np.arange(8).reshape(2,4)
a=np.ones_like(i)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [7]:
new_list=[1,2,3,4]
A=np.array(new_list)
A

array([1, 2, 3, 4])

4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [8]:
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [9]:
a=np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [11]:

a = np.random.random(30)
mean = a.mean()

print("Random array given: ", a)
print("Mean of array given : ", mean)


Random array given:  [0.25270571 0.14128591 0.45538586 0.03227296 0.27038749 0.68066506
 0.6749441  0.31553167 0.02061965 0.39257074 0.76606775 0.60007766
 0.32059767 0.37029617 0.82095726 0.0237029  0.40127457 0.22718895
 0.477972   0.88542652 0.84721    0.03728406 0.49224246 0.08383325
 0.35121346 0.20369056 0.96867738 0.35629033 0.3262109  0.38470739]
Mean of array given :  0.40604301333280596


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [15]:

a=np.random.random((10,10))
min=a.min()
max=a.max()
print(" Random Array: ", a)
print("MinValue:", min)
print("MaxValue:", max)

10x10 Random Array:  [[0.57445307 0.99907109 0.50826341 0.09180356 0.44887771 0.76442244
  0.80644247 0.21605619 0.39786659 0.15881069]
 [0.82298046 0.61027879 0.88876447 0.49549865 0.44388836 0.06216169
  0.77619343 0.51731957 0.10981019 0.41617311]
 [0.04711588 0.67951994 0.50357111 0.73260326 0.9076616  0.51780837
  0.11015012 0.05818893 0.0459275  0.80945651]
 [0.94401191 0.73174409 0.55526701 0.50580756 0.38257703 0.97956671
  0.11521867 0.67858213 0.60874723 0.13052811]
 [0.00580032 0.39634337 0.87685709 0.35749929 0.25467856 0.62937349
  0.14968142 0.92379296 0.12004459 0.8897803 ]
 [0.19412087 0.15265259 0.46630741 0.21276939 0.23638761 0.75837435
  0.97044139 0.75041891 0.76714339 0.66131925]
 [0.85983855 0.07682534 0.5580504  0.41774248 0.79228502 0.98632173
  0.45664226 0.75765013 0.01722419 0.69323521]
 [0.90425536 0.65468452 0.62813961 0.99386666 0.5032677  0.22573514
  0.43110283 0.8570311  0.23024981 0.57974305]
 [0.95530932 0.58664405 0.71603432 0.22023999 0.17716588 0.

6. Create a zero array of size 10 and replace 5th element with 1.

In [17]:
a=np.zeros(10)
a[4]=1
print("Updated :", a)

Updated : [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [18]:
a=np.array([1,2,0,0,4,0])
reversed=a[::-1]
print("Original array: ", a)
print("reversed array: ", reversed)

Original array:  [1 2 0 0 4 0]
reversed array:  [0 4 0 0 2 1]


8.Create a 2d array with 1 on border and 0 inside.

In [20]:
a=np.zeros((5,5),dtype=int)
a[0,:]=1 #top
a[-1,:]=1 #bottom
a[:,0]=1 #left
a[:,-1]=1 #right
print("1 on border and 0 inside 2D ARRAY: \n",a)


1 on border and 0 inside 2D ARRAY: 
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


9.Create a 8X8 matrix and fill it with a checkerboard pattern.

In [22]:

a=np.zeros((8,8))
a[1::2,::2]=1
a[::2,1::2]=1
a



array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
x1 = np.array([9,10]) and y1 = np.array([11,12]);
Complete all the task using numpy:

1. Add the two array.

In [24]:
x=np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]])
x1 = np.array([9,10])
y1 = np.array([11,12])
print("x: \n",x)
print("y: \n",y)
add=x+y
add1=x1+y1
print("Adding x+y: \n",add)
print("x1: \n",x1)
print("y1: \n",y1)
print("adding x1+y1: ",add1)

x: 
 [[1 2]
 [3 5]]
y: 
 [[5 6]
 [7 8]]
Adding x+y: 
 [[ 6  8]
 [10 13]]
x1: 
 [ 9 10]
y1: 
 [11 12]
adding x1+y1:  [20 22]


2. Subtract the two array.

In [25]:
sub=x-y
sub1=x1-y1
print("subtracting y from x: ",sub)
print("subtracting y1 from x1: ",sub1)

subtracting y from x:  [[-4 -4]
 [-4 -3]]
subtracting y1 from x1:  [-2 -2]


3. Multiply the array with any integers of your choice.

In [26]:
mul_x=x*2
print("x: \n",mul_x)
mul_y=y*2
print("y: \n",mul_y)
mul_x1=x1*2
print("x1: \n",mul_x1)
mul_y1=y1*2
print("y1: \n",mul_y1)

x: 
 [[ 2  4]
 [ 6 10]]
y: 
 [[10 12]
 [14 16]]
x1: 
 [18 20]
y1: 
 [22 24]


4. Find the square of each element of the array.

In [ ]:
sq_x=np.square(x)
print("squaring x: \n",sq_x )
sq_y=np.square(y)
print("squaring y: \n",sq_y )
sq_x1=np.square(x1)
print("squaring x1: \n",sq_x1 )
sq_y1=np.square(y1)
print("squaring y1: \n",sq_y1 )




squaring x: 
 [[ 1  4]
 [ 9 25]]
squaring y: 
 [[25 36]
 [49 64]]
squaring v: 
 [ 81 100]
squaring w: 
 [121 144]


5. Find the dot product between

In [27]:
result_1 = np.dot(x1, y1)
print("Dot product of x1 and y1: \n", result_1)
result_2 = np.dot(x, x1)
print("Dot product of x and x1:\n", result_2)
result_3 = np.dot(x, y)
print("Dot product of x and y:\n", result_3)


Dot product of x1 and y1: 
 219
Dot product of x and x1:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate x1(and)y1 along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [28]:
a=np.concatenate((x,y),axis=1)
print("along row: \n",a)
a=np.vstack((x1,y1))
print("along column: \n",a)

along row: 
 [[1 2 5 6]
 [3 5 7 8]]
along column: 
 [[ 9 10]
 [11 12]]


In [29]:
result = np.concatenate((x, x1))
print("Concatenation result:\n", result)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

X here is a 2d array and x1 is 1d array.




Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A^−1 = I


In [30]:

A=np.array([[3,4],[7,8]])
B=np.array([[5,3],[2,1]])
A_inverse=np.linalg.inv(A)
result=np.dot(A,A_inverse)
identity_matrix=np.eye(2)
print("Matrix A:\n", A)
print("Inverse of A (A^-1):\n", A_inverse)
print("Product of A and A^-1 (A.A^-1):\n", result)
print("Identity Matrix:\n", identity_matrix)
y=np.allclose(result,identity_matrix)
print("Is A.A^-1 equal to identity matrix?->",y)


Matrix A:
 [[3 4]
 [7 8]]
Inverse of A (A^-1):
 [[-2.    1.  ]
 [ 1.75 -0.75]]
Product of A and A^-1 (A.A^-1):
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Identity Matrix:
 [[1. 0.]
 [0. 1.]]
Is A.A^-1 equal to identity matrix?-> True


2. Prove AB ̸= BA.

In [31]:
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB (A * B):\n", AB)
print("BA (B * A):\n", BA)
are_equal=np.array_equal(AB,BA)
print(" Is AB = BA? ",are_equal)

AB (A * B):
 [[23 13]
 [51 29]]
BA (B * A):
 [[36 44]
 [13 16]]
 Is AB = BA?  False


 3. Prove (AB)^T=B^T*A^T

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
AB=np.dot(A,B)
AB_T=AB.T
B_T=B.T
A_T=A.T
BT_AT=np.dot(B_T,A_T)
print("AB:\n", AB)
print("(AB)^T:\n", AB_T)
print("B^T:\n", B_T)
print("A^T:\n", A_T)
print("B^T * A^T:\n", BT_AT)
is_equal=np.array_equal(AB_T,BT_AT)
print("Is (AB)^T equal to B^T * A^T? ", is_equal)

AB:
 [[19 22]
 [43 50]]
(AB)^T:
 [[19 43]
 [22 50]]
B^T:
 [[5 7]
 [6 8]]
A^T:
 [[1 3]
 [2 4]]
B^T * A^T:
 [[19 43]
 [22 50]]
Is (AB)^T equal to B^T * A^T?  True


Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9
{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [32]:

A=np.array([[2,-3,1], [1,-1,2], [3,1,-1]])
B=np.array([-1,-3,9])
A_inverse=np.linalg.inv(A)
x=np.dot(A_inverse,B)
print("Coefficient Matrix (A):\n", A)
print("Constants Vector (B):\n", B)
print("Inverse of A (A^-1):\n", A_inverse)
print("Solution Vector (X):\n", x)

Coefficient Matrix (A):
 [[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
Constants Vector (B):
 [-1 -3  9]
Inverse of A (A^-1):
 [[ 0.05263158  0.10526316  0.26315789]
 [-0.36842105  0.26315789  0.15789474]
 [-0.21052632  0.57894737 -0.05263158]]
Solution Vector (X):
 [ 2.  1. -2.]


4.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:

1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [34]:

import time
l1=list(range(1,1000001))
l2=list(range(1,1000001))
start_time= time.time()
result_list=[a+b for a, b in zip(l1,l2)]
python_time=time.time()-start_time
print("Time taken using Python lists:", python_time, "seconds")
#numpy arrays:
a1=np.arange(1,1000001)
a2=np.arange(1,1000001)

start_time=time.time()
result_array=a1+a2
numpy_time=time.time()-start_time
print("Time taken  using NumPy arrays:", numpy_time, "seconds")



Time taken using Python lists: 0.10046625137329102 seconds
Time taken  using NumPy arrays: 0.014731168746948242 seconds


2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [35]:

start_time=time.time()
result_list=[a*b for a,b in zip(l1,l2)]
python_time=time.time()-start_time
print("multiplication using Python lists time:", python_time, "seconds")

start_time = time.time()
result_array = a1 * a2
numpy_time = time.time() - start_time
print(" multiplication using NumPy arrays:", numpy_time, "seconds")


multiplication using Python lists time: 0.10107111930847168 seconds
 multiplication using NumPy arrays: 0.005095005035400391 seconds


3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.

In [36]:



start_time = time.time()
dot_product_list = sum(a * b for a, b in zip(l1, l2))
python_time = time.time() - start_time
print("Time taken for dot product using Python lists:", python_time, "seconds")



start_time = time.time()
dot_product_numpy = np.dot(a1, a2)
numpy_time = time.time() - start_time
print("Time taken for dot product using NumPy arrays: ", numpy_time, "seconds")

Time taken for dot product using Python lists: 0.10902118682861328 seconds
Time taken for dot product using NumPy arrays:  0.001870870590209961 seconds


4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [38]:
import time
import numpy as np

# 1000 was taking long time so i did 100
# Python lists
m1 = [[i for i in range(100)] for j in range(100)]
m2 = [[i for i in range(100)] for j in range(100)]

start_time = time.time()
result_matrix = [[sum(m1[i][k] * m2[k][j] for k in range(100)) for j in range(100)] for i in range(100)]
python_time = time.time() - start_time
print("Matrix multiplication using Python lists time:", python_time, "seconds")

# Matrix multiplication using NumPy
m1_np = np.random.rand(100, 100)
m2_np = np.random.rand(100, 100)

start_time = time.time()
result_matrix_np = np.dot(m1_np, m2_np)
numpy_time = time.time() - start_time
print("Matrix multiplication using NumPy arrays time:", numpy_time, "seconds")


Matrix multiplication using Python lists time: 0.4346628189086914 seconds
Matrix multiplication using NumPy arrays time: 0.0004115104675292969 seconds
